from FrontEnd.Mainmethods import *  
#[0] frame 
#[1] width anchura del frame *
#[2] height altura del frame *
#[3] color del frame
#[4] texto del frame
#[5] font, fuentes  
#[6] tituloX posicion en el eje x del titulo 
#[7] tituloY posicion en el eje y del titulo
#[8] label de la url 
#[9] labelX posicion en el eje x del titulo 
#[10] labelY posicion en el eje y del titulo
#[11] search
#[12] searchX posicion en el eje x del titulo 
#[13] searchY posicion en el eje y del titulo
#[14] Button show [e-Flow, Citas, Encuestas, backPrincipal, funcion,Report ] 
#[15] Button  x   [e-Flow, Citas, Encuestas, backPrincipal, funcion,Report ] 
#[16] Button  y   [e-Flow, Citas, Encuestas, backPrincipal, funcion,Report ] 
#[17] funcion
#[18] texto de la funcion
#[19] funcion de busquedad
buttonReload = tk.Button(frame25, text="",image=reloadImg ,command=lambda:startingconfigureTicketPrintingService()).place(x=335,y=40)

#Funcion que se encarga de cargar los componentes basicos
def loadComponent(component):
  component[0].config(bg=component[3],width=component[1],height=component[2]) 
  Titulo = tk.Label(component[0],text=component[4],font=component[5],pady=12,bg=component[3])
  Titulo.place(x=component[6],y=component[7])
  component[8].config(text="",bg=component[3])
  component[8].place(x=component[9],y=component[10])
  if(component[11]):boton1 = tk.Button(component[0],text="Buscar", command=lambda:component[19]()).place(x=component[12],y=component[13])
  button6 = tk.Button(component[0], text="",image=confImg ,command=lambda: show_frame(component[0],frameConfiguracionColoresPrincipales)).place(x=375,y=40)
  if(component[14][0]):button2 = tk.Button(component[0],width=16,height=1, text="Back to e-Flow", command=lambda: show_frame(component[0],frameMenuEflow)).place(x=component[15][0],y=component[16][0])
  if(component[14][1]):button5 = tk.Button(component[0],width=16,height=1, text="Back to Citas", command=lambda: show_frame(component[0],frameMenuCitas)).place(x=component[15][1],y=component[16][1])
  if(component[14][2]):button7 = tk.Button(component[0],width=16,height=1, text="Back to Encuesta", command=lambda: show_frame(component[0],frameMenuEncuesta)).place(x=component[15][2],y=component[16][2])
  if(component[14][3]):button8 = tk.Button(component[0],width=16,height=1, text="Back to Inicio", command=lambda: show_frame(component[0],frameMenuPrincipal)).place(x=component[15][3],y=component[16][3])
  if(component[14][4]):button4 = tk.Button(component[0],width=16,height=1, text=component[18], command=lambda: component[17]()).place(x=component[15][4],y=component[16][4])
  if(component[14][5]):
    buttonExcel = tk.Button(component[0], text="",image=excel ,command=lambda: exportExcel()).place(x=340,y=55)
    buttonImpresora = tk.Button(component[0], text="",image=impresora ,command=lambda: show_frame(frame20b,frameConfiguracionColoresPrincipales)).place(x=305,y=55) 

component=[[frameMenuPrincipal,                    widthMenuPrincipal,heightMenuPrincipal,colorMenuPrincipal,          nameMenuPrincipal                                 ,fontMenuPrincipal     ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,False,False,False],[0,0,0,0,90]       ,[0,0,0,0,150],        executeScript,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuEflow,                        widthMenuEflow,heightMenuEflow,colorMenuPrincipal,                  nameMenuEflow                                     ,fontMenuEflow         ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuClient,                       widthMenuClient,heightMenuClient,colorMenuPrincipal,                nameMenuClient                                    ,fontMenuClient        ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuCitas,                        widthMenuCita,heightMenuCita,colorMenuPrincipal,                    nameMenuCitas                                     ,fontMenuCita          ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuEncuesta,                     widthMenuEncuesta,heightMenuEncuesta,colorMenuPrincipal,            nameMenuEncuesta                                  ,fontMenuEncuesta      ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuReport,                       widthMenuReporteria,heightMenuReporteria,colorMenuPrincipal,        nameMenuReportes                                  ,fontMenuReporteria    ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuAuto,                         widthMenuAutomatizacion,heightMenuAutomatizacion,colorMenuPrincipal,nameMenuAuto                                      ,fontMenuAutomatizacion,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuML,                           425,350,colorMenumail,                                              nameMenuMail                                      ,fontMenuPrincipal     ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,False,False,False],[0,0,0,0,0]        ,[0,0,0,0,0],          loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuDiagnosis,                    widthMenuDiagnostico,heightMenuDiagnostico,colorMenuDiagnostico,    nameMenuDiagnostico                               ,fontMenuDiagnostico   ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuApi,                          widthMenuApi,heightMenuApi,colorMenuApi,                            nameMenuApi                                       ,fontMenuApi           ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[framesubMenuIIS,                       425,350,colorMenuiis,                                               namesubMenuIIS                                    ,fontMenuPrincipal     ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,False,False,False],[0,0,0,0,0]        ,[0,0,0,0,0],          loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frameMenuSuite,                        widthMenuSuite,heightMenuSuite,colorMenuSuite,                      nameMenuSuite                                     ,fontMenuSuite         ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,True,False,False], [0,0,0,230,0]      ,[0,0,0,270,0],        loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[framesubMenuNME,                       425,350,colorMenuNME,                                               nameSubMenuNME                                    ,fontMenuPrincipal     ,140,30,label1 ,40,125,False,0,0   ,[False,False,False,False,False,False],[0,0,0,0,0]        ,[0,0,0,0,0],          loadComponent,                       '',                          lambda:ExamineDirectory(label1)]
          ,[frame,                                 425,350,colorMenuservice,                                           nameMenuService                                   ,fontMenuPrincipal     ,75,0  ,label1 ,40,125,True ,40,150,[True,True,True,True,True,False]     ,[2.5,130,275,275,90],[270,270,270,240,150],executeScript,                      'Crear Script',              lambda:Examine(1)]
          ,[frame2,                                425,350,colorMenuiis,                                               nameMenuAIIS                                      ,fontMenuPrincipal     ,75,0  ,label2 ,40,125,True ,40,150,[True,True,True,True,True,False]     ,[2.5,130,275,275,90],[270,270,270,240,150],createAplication,                   'Crear Aplicacion',          lambda:ExamineDirectory(label2)]
          ,[frame3,                                425,350,colorMenuudl,                                               nameMenuUDL                                       ,fontMenuPrincipal     ,75,0  ,label3 ,40,125,True ,40,150,[True,True,True,True,True,False]     ,[2.5,130,275,275,90],[270,270,270,240,150],modifyUDL,                          'Modificar UDLS',            lambda:ExamineDirectory(label3)]
          ,[frame4,                                425,350,colorMenuport,                                              nameMenuPort                                      ,fontMenuPrincipal     ,75,0  ,label4 ,40,125,True ,40,150,[True,False,False,True,True,False]   ,[275,130,275,275,90],[270,270,270,240,150],modifyPort,                         'Modificar Puertos',         lambda:ExamineDirectory(label4)]
          ,[frame5,                                425,350,colorframe5,                                                nameMenuConfigCitas                               ,fontMenuPrincipal     ,75,0  ,label5 ,40,220,True ,40,270,[False,True,False,True,True,False]   ,[0,275,0,275,90]    ,[0,270,0,270,270],    modifyAppointment,                  'configurar citas',          lambda:ExamineDirectory(label5)]
          ,[frame6,                                425,350,colorMenuiis,                                               nameMenuSIIS                                      ,fontMenuPrincipal     ,75,0  ,label6 ,40,116,True ,40,135,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,240],createSite,                         'Crear Site',                lambda:ExamineDirectory(label6)]
          ,[frame7,                                425,350,colorMenuNcache,                                            nameMenuNCache                                    ,fontMenuPrincipal     ,40,0  ,label7 ,40,116,True ,40,135,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,270],modifyNCache,                       'Modificar NCache',          lambda:ExamineDirectory(label7)]
          ,[frame8,                                425,350,colorMenuNME,                                               nameMenuConfigNME                                 ,fontMenuPrincipal     ,40,0  ,label8 ,40,96 ,True ,40,115,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyNME,                          'Modificar NME',             lambda:ExamineDirectory(label8)]
          ,[frame9,                                425,350,colorMenuNME,                                               nameMenuConfigCitasNME                            ,fontMenuPrincipal     ,40,0  ,label9 ,40,96 ,True ,40,115,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyNMECitas,                     'Modificar NME',             lambda:ExamineDirectory(label9)]
          ,[frame10,                               425,350,colorframe5,                                                nameMenuRHI                                       ,fontMenuPrincipal     ,0,0   ,label10,40,96 ,True ,40,115,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyRHI,                          'Modificar Horario',         lambda:ExamineDirectoryRHI(label10)]
          ,[frame11,                               425,350,colorMenumail,                                              nameMenuCorreo                                    ,fontMenuPrincipal     ,40,0  ,label11,40,60 ,True ,40,80 ,[True,True,True,True,True,False]     ,[2.5,130,275,275,40],[270,270,270,240,235],modifyMail,                         'Modificar Correo',          lambda:ExamineDirectory(label11)]
          ,[frame12,                               425,350,colorframe5,                                                nameMenuConfigEncuesta                            ,fontMenuPrincipal     ,40,0  ,label12,40,220,True ,40,240,[False,False,True,True,True,False]   ,[275,130,275,275,90],[270,270,270,240,240],modifyPoll,                         'configurar Encuesta',       lambda:ExamineDirectory(label12)]
          ,[frame13,                               425,350,colorframe5,                                                nameMenuConfigTimeSesionConsole                   ,fontMenuPrincipal     ,40,0  ,label13,40,96 ,True ,40,115,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyConsoleSesion,                'Modificar tiempo',          lambda:ExamineDirectoryConsoleSesion(label13)]
          ,[frame14,                               425,350,colorMenuNME,                                               nameMenuConfigNMESite                             ,fontMenuPrincipal     ,40,0  ,label14,40,96 ,True ,40,115,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyNMESite,                      'Modificar NME',             lambda:ExamineDirectory(label14)]
          ,[frame15,                               425,350,colorframe5,                                                nameMenuEmissionConfig                            ,fontMenuPrincipal     ,160,0 ,label15,40,55 ,True ,40,240,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyNMEEmissionConfig,            'Modificar Emission.config', lambda:ExamineDirectoryNME(label15)]
          ,[frame16,                               425,350,colorframe5,                                                nameMenuNodo                                      ,fontMenuPrincipal     ,160,0 ,label16,40,36 ,True ,40,240,[True,False,False,True,True,False]   ,[275,130,275,275,40],[270,270,270,240,265],modifyNode,                         'Modificar nodo XML',        lambda:Examine(2)]
          ,[frame16b,                              425,350,colorframe5,                                                nameMenuNodo                                      ,fontMenuPrincipal     ,160,0 ,label16,40,36 ,True ,40,240,[False,False,False,False,False,False],[0,0,0,0,0]         ,[0,0,0,0,0]          ,loadComponent,                      '',                          lambda:ExamineDirectory(label17)]
          ,[frame17,                               425,350,colorframe5,                                                nameMenuAutomatizacion                            ,fontMenuPrincipal     ,160,0 ,label17,40,55 ,True ,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265],      automateProcess,                    'Automatizar',               lambda:ExamineDirectory(label17)]
          ,[frame18,                               425,350,colorframe5,                                                nameMenuReport                                    ,fontMenuPrincipal     ,160,0 ,label18,40,36 ,True ,40,55 ,[False,False,False,True,False,True]  ,[0,0,0,275,0]       ,[0,0,0,240,0]        ,loadComponent,                      '',                          lambda:ExamineDirectoryReporteria(label18)]
          ,[frame19,                               425,350,colorframe5,                                                nameMenuReportEflow                               ,fontMenuPrincipal     ,160,0 ,label19,40,36 ,True ,40,55 ,[False,False,False,True,False,True]  ,[0,0,0,275,0]       ,[0,0,0,240,0]        ,loadComponent,                      '',                          lambda:ExamineDirectoryReportesAplicativos(1,label19)]
          ,[frame20,                               425,350,colorframe5,                                                nameMenuReportCitas                               ,fontMenuPrincipal     ,160,0 ,label20,40,36 ,True ,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,150,25]      ,[0,0,0,270,270]      ,updateAppointment,                  'Actualizar datos',          lambda:ExamineDirectoryReportesAplicativos(2,label20)]
          ,[frame22,                               425,350,colorframe5,                                                nameMenuReportVirtualQueue                        ,fontMenuPrincipal     ,40,0  ,label22,40,36 ,True ,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,0]       ,[0,0,0,240,0]        ,loadComponent,                      '',                          lambda:ExamineDirectoryReportesAplicativos(3,label21)]
          ,[frame20b,                              425,350,colorframe5,                                                nameMenuReportCitasConfig                         ,fontMenuPrincipal     ,65,0  ,label20,40,36 ,False,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,150,25]      ,[0,0,0,270,270]      ,updateAppointment,                  'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame20c,                              425,350,colorframe5,                                                nameMenuReportCitasMSMQ                           ,fontMenuPrincipal     ,130,0 ,label20,40,36 ,False,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,150,25]      ,[0,0,0,270,270]      ,updateAppointment,                  'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame20d,                              425,350,colorframe5,                                                nameMenuReportCitasMoreConfig                     ,fontMenuPrincipal     ,130,0 ,label20,40,36 ,False,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,150,25]      ,[0,0,0,270,270]      ,updateAppointment,                  'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame21,                               425,350,colorframe5,                                                nameMenuReportEncuesta                            ,fontMenuPrincipal     ,145,0 ,label21,40,36 ,True ,40,55 ,[False,False,False,True,False,True]  ,[0,0,0,275,25]      ,[0,0,0,240,270]      ,updatePoll,                         'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame21b,                              425,350,colorframe5,                                                nameMenuReportEncuestaConfig                      ,fontMenuPrincipal     ,40,0  ,label21,40,36 ,False,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,275,25]      ,[0,0,0,240,270]      ,updatePoll,                         'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame22,                               425,350,colorframe5,                                                nameMenuReportVirtualQueue2                       ,fontMenuPrincipal     ,40,0  ,label22,40,36 ,False,40,55 ,[False,False,False,True,True,True]   ,[0,0,0,275,25]      ,[0,0,0,240,270]      ,updateVirtualQueue,                 'Actualizar datos',          lambda:ExamineDirectory(label1)]
          ,[frame23,                               425,350,colorframe5,                                                nameMenuDLL                                       ,fontMenuPrincipal     ,40,0  ,label23,40,86 ,True ,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingInstallDLL,                 'Instalar DLL',              lambda:ExamineDirectory(label1)]
          ,[frame24,                               425,350,colorframe5,                                                nameMenuInternetOption                            ,fontMenuPrincipal     ,40,0  ,label23,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingconfigureOptionInternet,    'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame25,                               425,350,colorframe5,                                                nameMenuTicketPrintingService                     ,fontMenuPrincipal     ,40,0  ,label25,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingUpdateTicketPrintingService,'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame26,                               425,350,colorframe5,                                                nameMenuAutoPlaylist                              ,fontMenuPrincipal     ,40,0  ,label23,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingconfigureAutoplaylist,      'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame27,                               425,350,colorframe5,                                                nameMenuResolution                                ,fontMenuPrincipal     ,40,0  ,label23,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingConfigureResolution,        'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame28,                               425,350,colorframe5,                                                nameMenuAutoLogon                                 ,fontMenuPrincipal     ,40,0  ,label23,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingConfigureAutoLogon,         'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame29,                               425,350,colorframe5,                                                nameMenuSI                                        ,fontMenuPrincipal     ,40,0  ,label29,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,275,40]      ,[0,0,0,240,265]      ,startingCreationScript,             'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frame30,                               425,350,colorMenuport,                                              nameMenuModificadorPuertoCitas                    ,fontMenuPrincipal,     75,0  ,label30,40,125,True ,40,150,[True,False,False,True,True,False]   ,[275,130,275,275,90],[270,270,270,240,150],modifyPortAppointment,              'Modificar',                 lambda:ExamineDirectory(label30)]
          ,[frame31,                               425,350,colorMenuport,                                              nameMenuDMSMQ                                     ,fontMenuPrincipal,     75,0  ,label30,40,125,False,40,150,[False,False,False,True,True,False]  ,[275,130,275,275,0],[270,270,270,270,150] ,validateMSMQ,                       'Diagnosticar',              lambda:ExamineDirectory(label30)]
          ,[frame32,                               425,350,colorMenuport,                                              nameMenuUnblockFile                               ,fontMenuPrincipal,     40,0  ,label32,0,95,  True ,0,120, [False,False,False,True,True,False]  ,[275,130,275,275,0],[270,270,270,270,150] ,startingUnblockingFolder,           'Desbloquear',               lambda:ExamineDirectory(label32)]
          ,[frame33,                               425,350,colorMenuport,                                              nameMenuTNC                                       ,fontMenuPrincipal,     75,0  ,label32,40,125,False,40,150,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,230],startingTest,                       'validar Conexion',          lambda:ExamineDirectory(label33)]
          ,[frame34,                               425,350,colorMenuport,                                              nameMenuConfigSuite                               ,fontMenuPrincipal,     75,0  ,label34,40,50 ,True ,40,70 ,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,230],startingConfigSuite,                'Configurar Suite',          lambda:ExamineDirectory(label34)]
          ,[frame35,                               425,350,colorMenuport,                                              nameMenuConfigSuiteBBDD                           ,fontMenuPrincipal,     75,0  ,label35,40,50 ,True ,40,70 ,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,230],startingConfigSuiteBBDD,            'Configurar BBDD',           lambda:ExamineDirectory(label35)]
          ,[frame36,                               425,350,colorMenuport,                                              nameMenuConfigSuiteIMCitas                        ,fontMenuPrincipal,     75,0  ,label36,4, 50 ,True ,4 ,60 ,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,230],startingConfigSuiteAppointment,     'Configurar Citas',          lambda:ExamineDirectorySuiteCitas(label36)]
          ,[frame37,                               425,350,colorMenuport,                                              nameMenuConfigApi                                 ,fontMenuPrincipal,     75,0  ,label36,40,125,False,40,150,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,270],startingRequest,                    'Realizar Request',          lambda:ExamineDirectory(label37)]
          ,[frame38,                               425,350,colorMenuport,                                              nameMenuSucApi                                    ,fontMenuPrincipal,     75,0  ,label38,40,125,False,40,150,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,270],startingRequest,                    'Realizar Request',          lambda:ExamineDirectory(label37)]
          ,[frame39,                               425,350,colorMenuport,                                              nameMenuDiagnosticoGeneral                        ,fontMenuPrincipal,     75,0  ,label39,20,70,True,  20,46,[False,False,False,True,True,False]  ,[275,130,275,275,10],[270,270,270,270,270],startingRequest,                    'Realizar Request',          lambda:ExamineDirectory(label39)]
          ,[frameConfiguracionColoresPrincipales  ,425,350,colorframeC,                                                nameMenuConfiguration1                            ,fontMenuPrincipal     ,50,0  ,label22,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,25,300]     ,[0,0,0,270,270]      ,saveDataConfiguration,              'Guardar',                   lambda:ExamineDirectory(label1)]
          ,[frameConfiguracionColoresSecundarios  ,425,350,colorframeC,                                                nameMenuConfiguration2                            ,fontMenuPrincipal     ,50,0  ,label22,40,36 ,False,40,55 ,[False,False,False,True,True,False]  ,[0,0,0,25,300]     ,[0,0,0,270,270]      ,saveDataConfiguration,              'Guardar',                   lambda:ExamineDirectory(label1)]]
setScript()

#Este es un egg easter
def on_key_pressed(event=None):
  k.config(text=str(ko(event,int(k.cget("text")))))
  if(int(k.cget("text"))==9):
    
    tk.messagebox.showinfo(title="codigo konami", message="FELICIDADES CRACK!!!!!,\nTE GANASTE EL ACCESO AL PUNTERO CHEAT ")
    loadColor("#D4AF37",component)
    menu.config(cursor="pirate")

#Funcion se encarga de mostrar el menu de configuracion
def showConfiguration(event=None):show_Configuration(component,frameConfiguracionColoresPrincipales)   
menu.bind('<Key>', on_key_pressed)
menu.bind_all("<Control-n>", new_Archive)
menu.bind_all("<Control-c>", showConfiguration )